CREATE DATABASE IF NOT EXISTS mahara CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'mahara'@'%' IDENTIFIED BY 'change-me';
GRANT ALL PRIVILEGES ON mahara.* TO 'mahara'@'%';
FLUSH PRIVILEGES;
